r_shoulder_y:
  ID: 1
  Return_Delay_Time: 0
l_shoulder_y:
  ID: 2
  Return_Delay_Time: 0
r_shoulder_x:
  ID: 3
  Return_Delay_Time: 0
l_shoulder_x:
  ID: 4
  Return_Delay_Time: 0
r_elbow_y:
  ID: 5
  Return_Delay_Time: 0
l_elbow_y:
  ID: 6
  Return_Delay_Time: 0
r_hip_z:
  ID: 7
  Return_Delay_Time: 0
l_hip_z:
  ID: 8
  Return_Delay_Time: 0
r_hip_x:
  ID: 9
  Return_Delay_Time: 0
l_hip_x:
  ID: 10
  Return_Delay_Time: 0
r_hip_y:
  ID: 11
  Return_Delay_Time: 0
l_hip_y:
  ID: 12
  Return_Delay_Time: 0
r_knee_y:
  ID: 13
  Return_Delay_Time: 0
l_knee_y:
  ID: 14
  Return_Delay_Time: 0
r_ankle_y:
  ID: 15
  Return_Delay_Time: 0
l_ankle_y:
  ID: 16
  Return_Delay_Time: 0
r_ankle_x:
  ID: 17
  Return_Delay_Time: 0
l_ankle_x:
  ID: 18
  Return_Delay_Time: 0
head_y:
  ID: 19
  Return_Delay_Time: 0
head_z:
  ID: 20
  Return_Delay_Time: 0